# Generated by Django 5.2.8 on 2025-11-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('chapters', models.ManyToManyField(blank=True, related_name='novels', to='core.chapter')),
            ],
        ),
    ]
