# Generated by Django 5.2.8 on 2025-12-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_novel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='user',
        ),
        migrations.AddField(
            model_name='novel',
            name='categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='novel',
            name='cover_image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='novel',
            name='status',
            field=models.CharField(default='Rascunho', max_length=50),
        ),
        migrations.AddField(
            model_name='novel',
            name='synopsis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='novel',
            name='title',
            field=models.CharField(default='Untitled', max_length=200),
        ),
    ]
