# Generated by Django 5.2.8 on 2025-12-02 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_novel_name_remove_novel_user_novel_categories_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
