# Generated by Django 4.2.7 on 2025-12-09 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_comment_like_favorite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='like',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='core.chapter'),
        ),
        migrations.AlterField(
            model_name='like',
            name='novel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='core.novel'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'novel', 'chapter')},
        ),
    ]
